version: '3'

services:
  mongodb:
    container_name: mongodb-api-mds
    restart: "no" # unless-stopped
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - data_mongodb:/data/db
    networks:
      - bridge

  api:
    depends_on:
      - mongodb
    container_name: api-mds
    build: ./api
    restart: "no" # unless-stopped
    ports:
      - 8088:8088
    volumes:
      - ./api/code:/usr/app
      - /usr/app/node_modules/
    networks:
      - bridge

networks:
  bridge:

volumes:
  data_mongodb:
